// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhP3itSxWhFHfbYTld69dMqoVxAFPo5NI',
    appId: '1:131692782874:web:abc00c3161153484f9f8a3',
    messagingSenderId: '131692782874',
    projectId: 'farmerhelp-4d27c',
    authDomain: 'farmerhelp-4d27c.firebaseapp.com',
    storageBucket: 'farmerhelp-4d27c.firebasestorage.app',
    measurementId: 'G-N9B6GREH4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iSAnB7yvmjYWBqVrzLtt6cp2IXUpoQM',
    appId: '1:131692782874:android:b7f70cd208406d19f9f8a3',
    messagingSenderId: '131692782874',
    projectId: 'farmerhelp-4d27c',
    storageBucket: 'farmerhelp-4d27c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3kCq9v35GHOm7mfLavGRNK2vzJ1hjKpE',
    appId: '1:131692782874:ios:03c90086fd6cf938f9f8a3',
    messagingSenderId: '131692782874',
    projectId: 'farmerhelp-4d27c',
    storageBucket: 'farmerhelp-4d27c.firebasestorage.app',
    iosBundleId: 'com.example.agrosaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhP3itSxWhFHfbYTld69dMqoVxAFPo5NI',
    appId: '1:131692782874:web:ed5a5b5243f84de1f9f8a3',
    messagingSenderId: '131692782874',
    projectId: 'farmerhelp-4d27c',
    authDomain: 'farmerhelp-4d27c.firebaseapp.com',
    storageBucket: 'farmerhelp-4d27c.firebasestorage.app',
    measurementId: 'G-1TJY7KPX0T',
  );
}
